# Generated by Django 6.1 on 2026-08-19 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
