# Generated by Django 6.1 on 2026-08-19 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="borrowing",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Borrowing",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
