# Generated by Django 6.1 on 2026-08-19 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
